name: Build and run

on: [push, pull_request]


jobs:
  conan_build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install tools
      run: |
        cmake --version
        python --version
        python -m pip install --upgrade pip
        python -m pip install conan
        conan --version
        conan config init

    - name: Adjust libcxx
      run: |
        conan profile update settings.compiler.libcxx=libstdc++11 default
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Compile
      run: |
        mkdir _build && cd _build
        conan install ../conanfile.txt -s build_type=Release
        cmake .. -DCMAKE_MODULE_PATH=$(pwd)
        cmake --build . --config Release

    - name: Run tests
      working-directory: _build
      run: |
        ./bin/wt-example --help
